Feature/open graph meta data
Healthy-London-Partnership/frontend pull request #26
Opened 2020-10-01 15:22 UTC by seanjessen

### Summary
https://trello.com/c/fazlTA1V/119-add-open-graph-meta-data-to-all-pages-templates

Added a dynamic component to display unique meta data for each route. If meta data isn't set it will use the default meta data

### Development checklist
- [x] The individual routes should display unique meta data if it has been added in the view using the MetaData component

### Release checklist
N/A

### Notes
This component will probably be updated as we go along and more specific route based data is needed. There is the potential to integrate this with fields in the CMS in the future to set the different meta tags e.g. for each service or collection

2020-10-01 19:33 UTC, matthew-inamdar requested changes
Looks good 👍 

Some minor changes requested.

2020-10-01 19:33 UTC, matthew-inamdar commented on src/views/Results/Results.tsx
> +    console.log(resultsStore);
Please remove

```suggestion
```

2020-10-01 19:33 UTC, matthew-inamdar commented on src/views/Service/Service.tsx
> +          metaDescription={service.description}
Can the OG image be provided here?

2020-10-01 19:49 UTC, seanjessen commented on src/views/Service/Service.tsx
> +          metaDescription={service.description}
There are props for all meta tags within the MetaData component but we don't have assets for this yet. I discussed this with @AyupMike and we agreed this would be adhoc as we go along and get content.

2020-10-01 19:52 UTC, seanjessen commented on src/views/Results/Results.tsx
> +    console.log(resultsStore);
This has now been removed

2020-10-05 08:07 UTC, matthew-inamdar approved these changes
LGTM 👍

2020-10-05 08:07 UTC, merged